### ISSUE TITLE
TXD/TEX Format: Handler needed

### ISSUE THREAD

**Issue by Sor3nt** [Sor3nt/manhunt-toolkit#11]
Also here we have the struct and need to build a unpacker

//--------------------------------------
//--- 010 Editor v4.0.1 Binary Template
//
// File: Manhunt 2 TXD/TEX Format
// Author: Allen(Leeao)
// Revision:
// Purpose: Textures
//--------------------------------------
struct
{
    char    TCDT[4];//MagicNumber
    DWORD   constNumber;//const is 1
    DWORD   fileSize;
    DWORD   indexTabelOffset;//Main offsets table
    DWORD   indexTabelOffset2;// offset = offset2
    DWORD   numIndex;//number of offsets
    DWORD   zero1;
    DWORD   zero2;
    DWORD   numberTextures;
    DWORD   FirstTexturesOffset;
    DWORD   LastTexturesOffset;
    DWORD   zero3;

}texHeader;
    FSeek(texHeader.FirstTexturesOffset);
local int i;
for (i=0;i<texHeader.numberTextures;i++)
{
    struct {
        DWORD   nextTexturesOffset;
        DWORD   PrevTexturesOffset;
        char    texturesName[0x20];
        byte    AlphaFlag;//1 is Alpha , 0 is no
        char    Padding[0x1F];
        DWORD   texturesWidth;
        DWORD   texturesHeight;
        DWORD   BitPerPixel;
        DWORD   PitchOrLinearSize;
        WORD    Flags;
        WORD    unknown;
        byte    MipMapCount;
        byte    padding[3];
        DWORD   texturesDataOffset;//PC is DDS File Offset
        DWORD   PaletteDataOffset;//PC disable
        DWORD   DDSFileSize;//PC is DDS File Size, PSP disable
        DWORD   zero2;
    }texEntryHeader;    
    FSeek(texEntryHeader.nextTexturesOffset);
}

**Comment by guard3** [comment]
The first part of the header looks like a standard R*Leeds relocatable chunk header

**Comment by Sor3nt** [comment]
unpacker implemented, packer will not be a part of MHT, exists already very good tools for this

**Comment by Sor3nt** [comment]
we need a tex handler for the IDE...

**Comment by Sor3nt** [comment]
TEX unpacker added with DXT1 and DXT5 support, output to BMP, packing not supported right now

**Comment by Sor3nt** [comment]
PSP and PS2 also added, WII missed....

**Comment by majesticR3** [comment]
Structures is a mess. I use this for PS2 and PSP version in my tools:

Pascal:

type
  PChunkHeader = ^TChunkHeader;
  TChunkHeader = packed record
    Ident: LongWord; //TDCT in manhunt2
    Shrink: LongWord;
    FileEnd: LongWord;
    DataEnd: LongWord;
    RelocTab: LongWord;
    NumRelocs: LongInt;
    GlobalTab: LongWord;
    NumClasses: Word;
    NumFuncs: Word;
  end;

  PRslTextureNativeStruct = ^TRslTextureNativeStruct;
  TRslTextureNativeStruct = packed record
     Next: PRslTextureNativeStruct;
     Prev: PRslTextureNativeStruct;
     TextureName: array[0..31] of Char;
     MaskName: array[0..31] of Char;
     Width: LongWord;
     Height: LongWord;
     Depth: LongWord;
     Stride: LongWord; // Texture width in bytes. Small textures can have aligned stride (8 for example for 4bit 8x8 textures)
     RasterFormat: Word;
     TilingMask: Word; // color ramps 32bpp texture have this flag to store untiled
     NumMipMaps: Byte;
     SwizzlingMask: Byte; // Used in ps2 version. Each bit from less significant defines PSMT8 swizzling usage for mip-map level
     Padding: Word;
     Pixels: Pointer;
     Patette: Pointer;
  end;

  PRslTextureDictionary = ^TRslTextureDictionary;
  TRslTextureDictionary = packed record
     NumTextures: LongInt;
     Next: PRslTextureNativeStruct;
     Prev: PRslTextureNativeStruct;
  end;

**Comment by Sor3nt** [comment]
implemented
