### ISSUE TITLE
Cannot extract *.ifp (v 0.6.0)

### ISSUE THREAD

**Issue by SkullKid2000** [Sor3nt/manhunt-toolkit#20]
I get the output "Expected SEQT or SEQU got: H". Do you know why this happens, Sor3nt? It's Skull Kid from the Project Manhunt forum.

**Comment by Sor3nt** [comment]
Hm looks like the ifp is broken ?

maybe its a wrong game detection, you could try to add the flags for game and platform like this

`mht unpack file.ifp --game=mh2 --platform=pc`

if this not help, please provide the problem file

**Comment by SkullKid2000** [comment]
Then I get "Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in D:\MHT\src\Service\NBinary.php on line 105". 

Strange indeed. Although I previously used v 0.1.0. That one worked though. It may be that this one needs more commands...

**Comment by SkullKid2000** [comment]
For your information, it is the file allanims.ifp in the levels\attic level.

**Comment by Sor3nt** [comment]
Yea alright, you should increase your memory inside the php.ini , set memory_limit to -1 and the error should be gone.

yea the IFP got many changes and fixes thats why its different between mht 0.1 and 0.6.

the file works with following command (+ memory limit set to -1)

<img width="936" alt="bildschirmfoto 2019-02-16 um 18 41 10" src="https://user-images.githubusercontent.com/1684233/52903211-82697a80-321a-11e9-8cac-92b7f2828966.png">

**Comment by Sor3nt** [comment]
but still, mht has here a game/platform auto detection issue, thanks for reporting it

**Comment by SkullKid2000** [comment]
> but still, mht has here a game/platform auto detection issue, thanks for reporting it

No problem Sor3nt. It's a bit of a relief being here instead of over at the Project Manhunt forum. Kind of childish behavior over there.

I wish you good luck with the development of the Manhunt Toolkit :)
