### ISSUE TITLE
Use your tool to generate GXT can import the runaway governor were the wii mirror to use?

### ISSUE THREAD

**Issue by toutheif** [Sor3nt/manhunt-toolkit#21]
As shown, there is a problem, use your tool to edit the wii GXT, runaway governor were the Chinese cannot save success, how to deal with? Thank you, novice counseling

**Comment by Sor3nt** [comment]
thats maybe because MHT just pack to PC and never to a other platform. MHT can extract any platform but not packing TO any.

Feel free to join our chat at https://discord.gg/xMAJvPn
