### ISSUE TITLE
Packing .glg files does not work

### ISSUE THREAD

**Issue by improvised-explosive-device** [Sor3nt/manhunt-toolkit#30]
Packing a .glg file seems to do nothing but add a newline at the start of the file, however your tool https://github.com/Sor3nt/Manhunt2-glg works great.

**Comment by Sor3nt** [comment]
depends on the version, if u use the master mht.phar, unpacking a glg will create a folder structure which will be packed back into a glg.

the older versions just unzip it, once unzipped nothing happens anymore with the file.

anyway, you should checkout also the latest project, MHS :) https://www.dixmor-hospital.com/mhs/index.php

Happy Modding!
