### ISSUE TITLE
Support for FONT.DAT?

### ISSUE THREAD

**Issue by santiago046** [Sor3nt/manhunt-toolkit#31]
_Perhaps unnecessary for a file that most users would not modify._

**Comment by Sor3nt** [comment]
Sure, do you know the structure ? I have no idea :/

**Comment by Sor3nt** [comment]
never mind, here is the structure, was not hard to find it out but still, no idea what the fields are for, feel free to play around to find it out :)

`char fourCC[6];
int table1Count;
int zero[2];
int table2Count;
int unk3;
float flt;
int table1[table1Count];

int count2;

struct {
  int id;
  float matrix[5];
}table2[table2Count] <optimize=false>;
`

**Comment by santiago046** [comment]
Thanks! If I find something out, I will come back.

**Comment by santiago046** [comment]
There are three fonts:
```
- font0 — missing from GLOBAL.TXD or maybe it is t16plus;
- font1;
- font2.
```
And yes, you guessed right. After playing a little with FONT.DAT, I think the matrix field is:
```
char width in the screen;
char x offset start;
char y offset start;
char x offset end;
char y offset end.
```

**Comment by Sor3nt** [comment]
alright, will add a generic handler for the font

**Comment by Sor3nt** [comment]
can you gimme more infos from your testing ? i assume u tested the first entry from font 2 ? can you tell me the order of the chars ? is the first one "!" and second "6" or it is "`" ?

can not run mh right now :/ love my mac m2 -.-

**Comment by santiago046** [comment]
The first one is the space (0x20000000), followed by `!` (0x21000000) and so on.

**Comment by Sor3nt** [comment]
so this is the correct structure
       

struct {

        char sixCC[6];
        
        int charCount;
        int minChar; //minimum char code to apply font, always 0
        int fontIndex; //1,2 or 3
        int matrixCount;
        int unk; //unused
        float fontHeight;
        
        int characterMap[charCount + 1];
        
        struct {
          int keyIndex; //refer to characterMap
          float width; //width is calced by x2-x1 / 2
          float position[4]; //x1, y1, x2, y2; require scale factor
        }character[matrixCount] <optimize=false>;
    }Font[3] <optimize=false>;

There happens some scaling on the position matrix. i need to calculate it somehow or the output would be worthless since you can not add new char without millions try&errors to figure out the correct xyz1/xyz2 values

will take some time to reverse the exe handler

**Comment by santiago046** [comment]
Thanks to Bing AI, I figured out how the calculation is done. It's quite simple: you need to take the positions and multiply them by the dimensions of the texture source which is 256x256. If the texture was 256x512, I think that would require to calculate x1/x2 by 256 and y1,y2 by 512.

**Comment by santiago046** [comment]
I don't know if GitHub notifies edited comments, so I will make a new one: that also applies to `fontHeight`, to get its actual value multiply it by 256.

**Comment by Sor3nt** [comment]
Alright, that also mean we can not "just" unpack the font.dat, it always require the TXD which contains the original font to get correct size.

i will handle this like the audio stuff, the unpacking need to be done in the original folder and the process will look around for the required txd to get the sizes

same with packing, the image need to be there to calculate the values

**Comment by Sor3nt** [comment]
yea i added psp support, should be the same as ps2 but did not tried it

**Comment by santiago046** [comment]
> yea i added psp support, should be the same as ps2 but did not tried it

Strangely, when I run `manhunt-toolkit/mht.phar pack GLOBAL\#TXD mh2 psp` it throws:
```
Fatal error: Uncaught Exception: No handler available for file GLOBAL\#TXD…
```

**Comment by Sor3nt** [comment]
well it is more like a hack ^^ u need to use the (undocumented feature) raw

`
mht.php PICLOAD.TXD mh2 psp -raw
mht.php export/PICLOAD\#TXD mh2 psp -raw
`

it is only useful if you want to copy over textures, a "real" packing from png is not possible at the moment, we loose to much informations

**Comment by santiago046** [comment]
Oh, I see. Thanks.

**Comment by Sor3nt** [comment]
yea alright, that looks very good with the font.dat. thx

thinking about the best way to export it, maybe MHT should cut any the texture into single char.png and named like the hexcode. so we can easy adjust every char without to mess in whole texture.

any other ideas ?

**Comment by santiago046** [comment]
Cutting the texture into pieces per char? It can work, but when I was searching for MH2's [charset](https://github.com/santiago046/manhunt2-translation-resources/blob/main/font-and-charset-info.md#manhunt-2-charset-en-fr-ge-it-sp), I found some characters are “blank” or not mapped correctly (a guess) in the font textures.

I was thinking about extracting the whole texture in PNG and the fonts info to a JSON, something like that:
```json
{
    "fontID": 0,
    "fontHeight": 15,
    "characters": [
        "\u0020": [
            "startX": 0,
            "startY": 0,
            "endX": 10,
            "endY": 10
        ] 
    ]
}
```
The user would modify the font in Photoshop, for example, and them manually adjust the values in fonts_data.json.

**Comment by Sor3nt** [comment]
no one want to mess around with xy coordinates ^^ splitting the texture into single char images and rejoin them to generate a FONT.DAT and the texture is the easiest way i guess.

we can then adjust a single char-image and repack it without to fight with any xy values

i will give it a try
and yea you was right

        if ($fontIndex === 0) $textureName = "t16plus.dds";
        if ($fontIndex === 1) $textureName = "font2.dds";
        if ($fontIndex === 2) $textureName = "font1.dds";

**Comment by santiago046** [comment]
So, I am writing a Python script that takes a TTF/OTF and creates a PNG texture and a FONT.DAT of it:
![mh2-font-test](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/4d4d5027-c096-4785-b46a-364cebe839ff)

**Comment by Sor3nt** [comment]
nice ! yea it works actual fine, the unpacker creates now the single font char images and the packer recreate the texture and also font.dat but i struggle with some paddings between the chars, some chars require 1px padding, some needs 2px
could not find out yet why or for what.

well it is not required at all but mht always try to repack the given files 100%

will give it another try, worst case i ignore it 🤷

**Comment by santiago046** [comment]
Does the padding occur in height or width? Or in both cases?

From my testing with my font creator, it's also possible to add characters with ID higher than 255. For that, would be necessary to change the font resolution to fit all chars in the texture.

I never tested, but I guess it's possible to replace textures with different resolution than the original ones in PC version — do Wii too? — but not for PSP/PS2 because the tools available to edit the TXDs cannot change the resolution, right?

**Comment by Sor3nt** [comment]
padding is only between single chars so far i can see. it appear totally random, it is not a typical "byte padding".
Will do later a screenshot of it.

process for (unpack and repack) is actual done, just want the last percent (padding) :D 

i handle the 255 a little bit different, i check the highest given keycode and this deine the end, not sure if there is a cap inside the exe by 255.

before i release the new version i want to add UTF-16 support, the exe can handle it.
we have 4 bytes for each char available.

dIfferent resolution should work fine but yea i also never tested it, we will see :)

Did you checked the WII and PSP version ? everywhere the same font.dat struct?

**Comment by Sor3nt** [comment]
<img width="759" alt="Bildschirmfoto 2023-06-26 um 10 45 38" src="https://github.com/Sor3nt/manhunt-toolkit/assets/1684233/f166645a-406d-4fde-ac5e-6c38eb125719">

i placed the single chars onto the original image
you see, there is sometime 1p,  2px or 0px padding

**Comment by santiago046** [comment]
Right now, I have only the function but I already have some ideas for the CLI.


The function takes these arguments: texture resolution, font path, point size and the font index. There's so much arguments and they will change for 3 fonts. Maybe the user will need to pass always three values for each argument and loop through them.

It also has a charset, which is a Python dictionary that maps key codes to characters, like this:
```python
{
    32: " ",
    33: "!",
    34: '"', # double quote inside of single quotes
…
    256: "Ã", # Rockstar always excludes me and my relatives :(
}
```
I will implement this in my Python GXT Tool too.


Some key codes are reserved for GXT tokens and PlayStation buttons, and they cannot be changed. For example:
```python
{
    250: '®', # ~(R)~
    251: '©', # ~(C)~
    254: '™', # ~TM~
}
```

The function determines the char count and the matrix count based on the max key code in the charset. The matrix count is `charcount + 1`. It also need to create empty matrices for non-printable or undefined chars when looping through the matrix count.

**Comment by Sor3nt** [comment]
hm, anything is done but MHT does not support packing PNG to TEX xD MHT has only DDS to TEX but no PNG to DDS xD

how did you put back the texture ? exported as TGA an then used majestic tex tool ?

**Comment by santiago046** [comment]
Yes, it exported as TGA, then I imported/replaced it by t16plus using Majestic TEX/TXD Tool.

I undestand that MHT doesn't support PNG to DDS, it's a complex thing to implement 😅. Working with texture compression is a headache.

**Comment by Sor3nt** [comment]
hmmm well then we reached the point where MHT needs to support real MDL DDS 🤷 
i can not export my images as TGA. it would be anyway just a workaround.

will add png to DXT5 (DDS) and also jpeg to DXT1 support.

that is the only real way to get a smooth feature

**Comment by santiago046** [comment]
**MDL** DDS 🧐.

I need to check the texture size limits of MH2. I tried to import a 4096x4096 texture — yes, too much for this type of texture, but it doesn't hurt to test a “4K” font — but I don't know if it crashed or was processing/compressing the texture.

Right now, I am still trying to deal with the PS buttons in my tool. I guess I have to manage them separately from the drawing char loop.

**Comment by Sor3nt** [comment]
TEX DDS *g* sry it was late

there is actual no size limit, only the memory heap limit which can be adjusted, we have somewhere a version which allows to load up to 4gb of data

uhm what the issue with the PS button ? because of the used charcode ?!

**Comment by santiago046** [comment]
Well, the thing with the PS buttons is that I will need to handle differently them when adding in the font texture. The “normal” charset uses the drawing text mode of Pillow, but when it's the buttons, it needs to resize their textures and paste into the main texture.

**Comment by santiago046** [comment]
> Did you checked the WII and PSP version ? everywhere the same font.dat struct?

A friend of mine extracted the Wii one: it's the same format, but big endian instead. Here is:
[font.dat](https://github.com/Sor3nt/manhunt-toolkit/files/11910312/font.dat.txt)

**Comment by Sor3nt** [comment]
thx, no i did not check them yet but i will add them to.

i looked around and it is really a nightmare to create dxt stuff on the fly. 
guess will add a dependency, imagemagick or similar which can handle the stuff well

**Comment by Sor3nt** [comment]
alright nice, next update contains the full dds support, mht export dxt1 as jpg and dxt5 as png, repacking them works fine.
NOW i can finally finish the font packing 😂 

what a hell... for a font ... 😂

**Comment by santiago046** [comment]
Great 🙏. It's the art of programming: sometimes it's fun, other times stressful.

About the texture exporting: will it not DDS (DXT1) -> JPG add extra artifacts due to compression? It would be 3 compression layers when exporting and repacking: from .TEX, JPG, then DXT1.

I finished the PS buttons handling in my tool. Now it's time to (try to) rewrite the code in a better way and create the CLI. I have no idea when I will release it publicly due to another project I am in, but I will make sure to make it clear that I got your help, like with the structure.

**Comment by Sor3nt** [comment]
the .tex is just a container which holds the DDS, so it would be only DXT1<->JPG, we will not see any compression issues until we repeat the process multiple times 

but overall i agree, what should we use ? TGA ? BMP ? ^^

i just pushed the current MHT version which has font support for all platforms. also the texture handling changes are there. This solve also some alpha issues, maybe it solve already the other issue you raised.

feel free to test it, i will cleanup the code and add some "magic" functions (auto update texture file after font build...)

where can i find your code ? would love to see how you solved some "issues"

**Comment by santiago046** [comment]
Yep. If you want to keep it simple, you might consider using PNG for both types of textures, if not, BMP for non-alpha textures and PNG for alpha.

I will check out and comment about it in #32.

The unpacking for PSP looks okay. When repacking, it creates as `Textures`.

You will find my code probably at mh2-fontcreator repository in my profile when I release publicly. I'll let you know.

**Comment by santiago046** [comment]
Looks like that `uknInt` is the same as `font_height`, but in INT.

**Comment by Sor3nt** [comment]
hm this applies to font0 and font2 but not for font1, there we miss one px (30 vs 31) but guess this is just a result of manual work from r*

will apply the (scaled) font height as int and we should be good

should be the last task for this issue

**Comment by Sor3nt** [comment]
anyway, I just checked the binary in IDA, this byte (height as an int) is never read. so it is unused

**Comment by Sor3nt** [comment]
uhm which version do you try ?! works fine here

`
Game: mh2 | Platform: wii
Identify file as Font Coordinates
Processing /Users/sor3nt/www/privat/MANHUNT_GAME/Versions/wii_RHTE54/global/initscripts/font.dat ....................................................................................................................................................................................................................................................................................................................................................................................................................................................
Extracted to /Users/sor3nt/www/privat/MANHUNT_GAME/Versions/wii_RHTE54/global/initscripts/export/font#dat%               `

i use here RHTE54, i lost the other, maybe the USA version has another issue, pls post the font.dat

**Comment by santiago046** [comment]
I am using files from the USA redump of Manhunt 2 Wii. I actually just have the global folder, so I guess the error happens because I don't have the whole game files here.

Here is the [font.dat](https://github.com/Sor3nt/manhunt-toolkit/files/12044244/font.dat.txt) and [global_wii.txd](https://github.com/Sor3nt/manhunt-toolkit/files/12044247/global_wii.txd.txt)

**Comment by Sor3nt** [comment]
also works fine for me.

just pushed my uncommited changed but i looked at them and there are only cleanup, nothing what would raise a problem like this.

your error says 

Service/Archive/Font.php(81): App\Service\NBinary->consume(1, 'RAW')

but in L:81 is no RAW consume, that is a old version


pls update and try again 🤷

**Comment by santiago046** [comment]
I updated and, yeah, it's still happening.

Maybe it's a filesystem or permission thing, who knows…

I tried to get help with ChatGPT:
```
The error message indicates that there is a problem with the `substr()` function call in the `NBinary.php` file of the `mht.phar` application. The second argument passed to the `substr()` function should be an integer, but it is receiving a float value (`7553055486.0`).

To address this error, you can modify the `NBinary.php` file and ensure that the second argument passed to the `substr()` function is an integer. Here's what you can do:

1. Open the `NBinary.php` file in a text editor.
2. Locate the line mentioned in the error message: `substr('3c464f4e543e000...', 7553055486.0, 2)`.
3. Change the second argument from `7553055486.0` to `7553055486` (remove the decimal part and make it an integer).
4. Save the file and try running the `mht.phar` command again.

This modification should fix the error related to the `substr()` function.
```

I changed the 332th line of NBinary.php to `$result = hex2bin(substr($this->hex, intval($this->current * 2, $bytes * 2)));`, but it get terminated by signal SIGKILL.

**Comment by Sor3nt** [comment]
i added a workaround, pls try

but still, it is a mystery, which PHP version do u use on which OS ?

**Comment by santiago046** [comment]
Terminated by signal SIGKILL (force quit) again.


The value `7553055486.0` seems to be too high for me. What value do you get there? 

PHP version and OS:
```
~/ > PHP 8.2.8 (cli) (built: Jul  4 2023 23:31:24) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies

~/ > uname -a
Linux localhost 4.9.206-perf+ #1 SMP PREEMPT Fri Jan 29 05:24:25 CST 2021 armv7l Android
```

So, I am not really in a Linux OS, but Android instead using Termux.

**Comment by Sor3nt** [comment]
wth :D you work on a smartphone ? 🥇 

well i pushed another fix, pls try again

arm7 is 32bit so that should be fine

**Comment by santiago046** [comment]
Yep, it's painful sometimes because of the small screen size.

Well, no luck. Killed again. I think we should investigate this later, since it's working fine in your system. Should I create a new issue about this?

**Comment by Sor3nt** [comment]
hm no, there is no arm support for mht official xD 
i also can not debug it since i have no environment to test this.

it is a very edge case ^^

**Comment by Sor3nt** [comment]
🤷 pls try again, i pushed another "fix"

guess we can close the issue then

**Comment by santiago046** [comment]
The arm issue still persists, but as you said, we can close this issue as the main request has been completed.
