### ISSUE TITLE
Unpacked textures with alpha differs from PPSSPP dump

### ISSUE THREAD

**Issue by santiago046** [Sor3nt/manhunt-toolkit#32]
When unpacking TXDs from PSP — maybe from PS2 too —, textures with alpha shows different from the PPSSPP dump.

Left from mht, right from PPSSPP:
![font1extraction](https://user-images.githubusercontent.com/88282401/236843862-cabd70c3-4a9e-4baa-98e7-9332ec19b848.png)

Also, mht shows some warnings in the console output. If it helps: [cmdoutput.txt](https://github.com/Sor3nt/manhunt-toolkit/files/11421781/cmdoutput.txt)

**Comment by santiago046** [comment]
I tried with the european version (ULES-00756), but when I was making my PPSSPP texture pack, I remember the same thing happened with the US one.

If I recall correctly, this issue also happens with MAJEST1C_R3's editor tool.

[GLOBAL.TXD.txt](https://github.com/Sor3nt/manhunt-toolkit/files/11421853/GLOBAL.TXD.txt) — I had to append .txt to the extension for GitHub let me upload it.

**Comment by Sor3nt** [comment]
alright, thx will check it out after font.dat implementation

**Comment by santiago046** [comment]
Coming back here: when I was exploring it with the Majestic's TEX/TXD tool, It seems that in the PSP version, the color and alpha channels were reversed. When I selected “texture” it showed the alpha and vice versa.

**Comment by santiago046** [comment]
After 6bc0e354950ae0f91f5376bdc76b7611a29e8e86 commit, the warnings/errors are fixed, but the alpha issue still remains and introduced a new one: the ramps textures from GLOBAL.TXD looks bugged now:
![FE_colramps](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/3cdaee7e-4342-4a6e-8803-f64263c9f150) ![FE_dreamramps](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/1a39a814-93d5-4e41-90ef-5e640b2a81e2)

**Comment by Sor3nt** [comment]
alright, both fixed, the ramps required width*height*4 and no swizzle 🤷 
the initial issue with the font was a wrong fallback alpha value, i used 255 instead of 127 🙃

**Comment by santiago046** [comment]
Now the ramps are fixed, but:
![font2.png](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/17f47022-d851-470e-ba67-3f2f1555eaf8) ![FE_execramps.png](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/395dfad6-a1ac-4222-99d5-f318d50cbb81) ![FE_colramps.png](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/2e67c8b8-9058-4ae2-abc0-c905cb7dc3d8)

**Comment by Sor3nt** [comment]
stupid alpha values...

here we go
![font1](https://github.com/Sor3nt/manhunt-toolkit/assets/1684233/ea32dd93-8bbf-48aa-9b31-0e313bdf5e1a)

pushed

**Comment by Sor3nt** [comment]
hmmm guess my alpha decoding table is not correct

https://github.com/Sor3nt/manhunt-toolkit/blob/89e955ed3a137f9a7a84c22cb81e84e695b9b9ba/Application/App/Service/Archive/Textures/Playstation.php#L29

do you have any insides ?

**Comment by Sor3nt** [comment]
yea yea the table is wrong. total useless, i do not need it -.-

here we go 
![font1](https://github.com/Sor3nt/manhunt-toolkit/assets/1684233/f8dee534-f39a-42b7-8d4c-3a377ffeca3c)

pushed

**Comment by santiago046** [comment]
Just seeing now 😅 because of the world and its time zones.

Well, I personally could close this issue because there's no difference to the naked eye, however, I checked the MD5 values ​​and they differed.

Then, I had the idea to extract the alpha and color channels as different images:
![ORIGINAL.png](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/04007d7e-afe3-413f-8ce6-47b88f83b904) ![MH2.png](https://github.com/Sor3nt/manhunt-toolkit/assets/88282401/e244b46e-db92-4b41-a978-7a9ed279b3c2)

**Comment by Sor3nt** [comment]
hm i have no idea why this happens, looks like it has also no negative effects.

also, just pushed some fixes

can we close the issue ? :)

**Comment by santiago046** [comment]
We can consider it as issue fixed 👍.
