### ISSUE TITLE
Manhunt 1 unpack animations (IFP)

### ISSUE THREAD

**Issue by IXSkinzIX** [Sor3nt/manhunt-toolkit#36]
Everytime i try to unpack the animations from Manhunt 1 it always says Fatal Error... Im trying to replace the default player animations for the Hunter animations thanks.

**Comment by Sor3nt** [comment]
@IXSkinzIX fatal error could be anything, pls share full screenshot (mht call + error output)

**Comment by IXSkinzIX** [comment]
Okay sorry 
![Screenshot (15)](https://github.com/Sor3nt/manhunt-toolkit/assets/167111299/9b876040-b841-4d71-b861-c3176b29d405)

**Comment by Sor3nt** [comment]
@IXSkinzIX u missed to command xD guess u missed to tell MHT the platform and/or game... show me your command pls as well

**Comment by IXSkinzIX** [comment]
Ohhh XD here is the command
![Screenshot (16)](https://github.com/Sor3nt/manhunt-toolkit/assets/167111299/7d7da962-451d-4c42-ab37-ae6846d6e26e)

**Comment by IXSkinzIX** [comment]
Im trying to replace the default player animations for the Hunter animations

**Comment by IXSkinzIX** [comment]
Okay thank you i will test now

**Comment by IXSkinzIX** [comment]
It didnt work... can you give the command for Manhunt 1? and thank you

**Comment by Sor3nt** [comment]
show me the result (command + error output)
...

`php mht.phar allanims.ifp mh1 pc`

**Comment by IXSkinzIX** [comment]
![Screenshot (17)](https://github.com/Sor3nt/manhunt-toolkit/assets/167111299/7af3042e-5c5f-4941-8db2-115266328019)

**Comment by IXSkinzIX** [comment]
I typed the command but still the error

**Comment by IXSkinzIX** [comment]
![Screenshot (18)](https://github.com/Sor3nt/manhunt-toolkit/assets/167111299/88e8b473-56ea-4ce9-a40d-d519cd27b235)

**Comment by Sor3nt** [comment]
well i can just guess... are u using PHP8 ? If so, downgrade to PHP7... second... are u sure your file "allanims.ifp" is in the same folder ? if not you need to give MHT the full path to it like this: 

`php mht.phar d:\games\manhunt\levels\XYZ\allanims.ifp mh1 pc`

**Comment by IXSkinzIX** [comment]
Okay i will try that thank you

**Comment by IXSkinzIX** [comment]
Uhmm how can i give MHT the full path? sorry if this is a dumb question...

**Comment by Sor3nt** [comment]
`php mht.phar <FULL-PATH-TO-FILE> mh1 pc`

replace "<FULL-PATH-TO-FILE>" with the the actual file u want to extract 🤷

**Comment by IXSkinzIX** [comment]
Okay thanks and can i ask if you already have the Hunter animations for Manhunt 1? If so can you send them to me to test them in my game i would be eternal greatful

**Comment by IXSkinzIX** [comment]
It's because i would like to play as a actual hunter with hunter animations for my player character

**Comment by Sor3nt** [comment]
u are welcome
[allanims#ifp.zip](https://github.com/Sor3nt/manhunt-toolkit/files/14982613/allanims.ifp.zip)

**Comment by Sor3nt** [comment]
MHT does only provide support for Manhunt 1 & 2 , if you wanna port these to another game, i can not help ya 🤷

**Comment by IXSkinzIX** [comment]
Thats okay i understand i just want to play on  Manhunt 1 and 2

**Comment by IXSkinzIX** [comment]
Thank you once again

**Comment by IXSkinzIX** [comment]
Do i need to repack it?

**Comment by Sor3nt** [comment]
yea sure, it is the same command, MHT knows if u want to unpack or pack the given file

**Comment by IXSkinzIX** [comment]
Okay so i need to repack the GenHunterAnims right and then replace the allanims.ifp?

**Comment by Sor3nt** [comment]
you need to repack allanims#ifp and not a sub-folder, but yes u need to replace it then.

Manhunt modding is nothing for beginners, its damn fragile at any point, any mistake will result in fatal errors, you will need some time, try and error, to find a way that works for you

**Comment by IXSkinzIX** [comment]
Okay thanks

**Comment by IXSkinzIX** [comment]
Helloo again so do you know how can i replace Cash's model from Manhunt 1 on the ps2 emulator?

**Comment by Sor3nt** [comment]
uhm no sry, never tried this
