### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function mb_substr()

### ISSUE THREAD

**Issue by kordepits** [Sor3nt/manhunt-toolkit#40]
Fatal error: Uncaught Error: Call to undefined function mb_substr() in phar://C:/MHT/mht.phar/App/Service/NBinary.php:33Stack trace:
#0 phar://C:/MHT/mht.phar/App/Service/Resources.php(64): App\Service\NBinary->__construct('Z2HM\x94\x85\x0E\x00x\xDA\xEC\xBD\v\x80\e...')
#1 phar://C:/MHT/mht.phar/App/Commands/unpack.php(105): App\Service\Resources->load('C:\\A01_Escape_A...', 'mh2', 'pc')
#2 phar://C:/MHT/mht.phar/mht.php(113): include('phar://C:/MHT/m...')
#3 C:\MHT\mht.phar(10): include('phar://C:/MHT/m...')
#4 {main}
  thrown in phar://C:/MHT/mht.phar/App/Service/NBinary.php on line 33

**Comment by Sor3nt** [comment]
Enable mbstring in your php.ini
