### ISSUE TITLE
The problem with the execution of PSP 0.01 in PC

### ISSUE THREAD

**Issue by SemenS0** [Sor3nt/manhunt-toolkit#45]
I want to transfer the PSP 0.01 execution animation to the PC version, but I have a problem when I want to check, the game crashes when I want to execute help solve this problem

**Comment by Sor3nt** [comment]
wait a little, i work on MHS 2 which has in his first release PSP 001 to PC MDL support and next release  it will have animation as well.
its tricks 🤷

**Comment by SemenS0** [comment]
Oh, I understand your, but how long will it take to develop MHS 2

**Comment by Sor3nt** [comment]
hope to get done this year...

**Comment by SemenS0** [comment]
Damn good luck developing
